antora:
  extensions:
    - require: '@springio/antora-extensions'
      root_component_name: 'data-mongodb'
site:
  title: Spring Data MongoDB
  url: https://docs.spring.io/spring-data/mongodb/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
    - url: https://github.com/spring-projects/spring-data-mongodb
      # Refname matching:
      # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
      branches: [ main, '{4..9}.*({0..9}).x', '!4.0.x', '!4.1.x' ]
      tags: [ '({4..9}).+({0..9}).*', '!(4.0.*)', '!(4.1.*)','!4.2.0-M1','!4.2.0-M2' ]
      start_path: src/main/antora
    - url: https://github.com/spring-projects/spring-data-commons
      # Refname matching:
      # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
      branches: [ main, '{3..9}.*({0..9}).x', '!3.0.x', '!3.1.x' ]
      tags: [ '({3..9}).+({0..9}).*', '!(3.0.*)', '!(3.1.*)','!3.2.0-M1','!3.2.0-M2' ]
      start_path: src/main/antora
asciidoc:
  attributes:
    page-stackoverflow-url: https://stackoverflow.com/tags/spring-data-mongodb
    page-related-doc-categories: data
    page-related-doc-projects: framework,graphql
    hide-uri-scheme: '@'
    tabs-sync-option: '@'
  extensions:
    - '@asciidoctor/tabs'
    - '@springio/asciidoctor-extensions'
    - '@springio/asciidoctor-extensions/javadoc-extension'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/v0.4.18/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
    format: pretty
